### ISSUE TITLE
Availability of Preprocessing Files

### ISSUE THREAD

**Issue by j-bl** [batmanlab/TMLR23_Dynamics_of_Spurious_Features#1]
I have attempted to download the csv-files of the data preprocessing step such as [nih_full.csv](https://pitt-my.sharepoint.com/:x:/r/personal/nim123_pitt_edu/Documents/TMLR23_Dynamics_of_Spurious_Features/nih.csv?d=w1a6197caae734b35a9d2799032609cc9&csf=1&web=1&e=onM8L0). However, when accessing the link I encountered an authentication request for _pitt.edu_. Thus, the files for the data preprocessing appear to be unavailable without a login from the University of Pittsburgh.

Could you allow a download for users without a login? Thank you in advance!

**Comment by kayhan-batmanghelich** [comment]
Nihal

Can you provide the csv file.

**Comment by Nihal-M** [comment]
Sorry, I didn't realize there was a permissions issue. I fixed it. All links must be viewable now.

**Comment by j-bl** [comment]
Yes, I can access the files now - Thanks a lot for the quick help!
